INSERT INTO dreamjournal.dreams (user_id, title, content, tags, privacy, created_at) VALUES
                                                                                         (1, 'Flying Over Mountains', 'I dreamt that I was flying over beautiful mountains and valleys.', 'flying, mountains, nature', 'PUBLIC', '2025-02-19 08:30:00'),
                                                                                         (2, 'Lost in a Maze', 'I was lost in a giant maze and couldn\'t find my way out.', 'maze, lost, adventure', 'PUBLIC', '2025-02-18 22:15:00'),
                                                                                         (3, 'Talking Animals', 'I had a conversation with talking animals in a magical forest.', 'animals, forest, magic', 'PUBLIC', '2025-02-17 07:45:00'),
                                                                                         (4, 'Underwater City', 'I explored an underwater city filled with mermaids and sea creatures.', 'underwater, city, mermaids', 'PUBLIC', '2025-02-16 14:20:00'),
                                                                                         (5, 'Time Travel', 'I traveled back in time to the medieval era and witnessed a jousting tournament.', 'time travel, medieval, jousting', 'PUBLIC', '2025-02-15 19:00:00'),
                                                                                         (6, 'Alien Encounter', 'I met friendly aliens who showed me their advanced technology.', 'aliens, technology, space', 'PUBLIC', '2025-02-14 03:30:00'),
                                                                                         (7, 'Winning the Lottery', 'I won the lottery and became a millionaire overnight.', 'lottery, millionaire, money', 'PUBLIC', '2025-02-13 10:00:00'),
                                                                                         (8, 'Haunted House', 'I explored a haunted house and encountered ghosts and spirits.', 'haunted, ghosts, spirits', 'PUBLIC', '2025-02-12 23:45:00'),
                                                                                         (9, 'Superpowers', 'I discovered that I had superpowers and used them to save people.', 'superpowers, hero, saving', 'PUBLIC', '2025-02-11 16:30:00'),
                                                                                         (10, 'Vacation in Paris', 'I went on a vacation to Paris and visited the Eiffel Tower.', 'vacation, Paris, Eiffel Tower', 'PUBLIC', '2025-02-10 12:00:00'),
                                                                                         (11, 'Istenesen bebioztam', 'Kinyult a plugom geco nincs kitol vegyek zazat igy marad a bio.', 'vacation, Paris, Eiffel Tower', 'PUBLIC', '2025-02-10 12:00:00'),
                                                                                         (11, 'Istenesen bebioztam', 'LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE LOREM IPSUM SZOPOLE ', 'vacation, Paris, Eiffel Tower', 'PUBLIC', '2025-02-10 12:00:00');