
INSERT INTO users (username, email, password, profile_picture, bio) VALUES
                                                                        ('john_doe', 'john.doe@example.com', 'password123', 'default', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'),
                                                                        ('jane_smith', 'jane.smith@example.com', 'password456', 'default', 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'),
                                                                        ('alex_williams', 'alex.williams@example.com', 'password789', 'default', 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'),
                                                                        ('emily_brown', 'emily.brown@example.com', 'passwordabc', 'default', 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.'),
                                                                        ('michael_johnson', 'michael.johnson@example.com', 'passwordxyz', 'default', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
                                                                        ('sarah_lee', 'sarah.lee@example.com', 'passwordqwerty', 'default', 'Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit, nec luctus magna felis sollicitudin mauris.'),
                                                                        ('daniel_garcia', 'daniel.garcia@example.com', 'password12345', 'default', 'Phasellus euismod quam vel felis luctus, eu tincidunt velit euismod. Fusce tincidunt felis quis risus gravida, in auctor nisi fermentum.'),
                                                                        ('laura_davis', 'laura.davis@example.com', 'password67890', 'default', 'Nulla facilisi. Integer vel sapien sed lorem vestibulum vehicula. Nam sit amet ante et purus vestibulum gravida.'),
                                                                        ('david_martinez', 'david.martinez@example.com', 'passwordqwerty', 'default', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Etiam in leo quis libero sollicitudin vestibulum.'),
                                                                        ('olivia_moore', 'olivia.moore@example.com', 'password11111', 'default', 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.'),
                                                                        ('admin', 'admin@hugyos.com', 'admin', '1cc2be0b-06b4-416a-9006-48c3f85562cb.png', 'KIAKAROOOOOOOOOLY');